# THISCLOUD Calamares global configuration.
# Installed to /etc/calamares/settings.conf on the live system.
---
modules-search: [ local ]

# No custom instances; every module uses its implicit instance.
#instances: []

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - timezone
  - partition
  - users
  - network
  - thiscloudqml
  - summary
- exec:
  - partition
  - mount
  - unpackfs
  - fstab
  - locale
  - keyboard
  - localecfg
  - users
  - networkcfg
  - hwclock
  - services-systemd
  - initramfs
  - bootloader
  - thiscloud
  - umount
- show:
  - finished

branding: thiscloud