/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/openapi.yaml": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** This contract (OpenAPI) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The OpenAPI document served by this daemon */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/yaml": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check (liveness) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example ok */
                            status?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness check
         * @description Reports whether the daemon is ready to serve traffic. Checks the
         *     dependencies the daemon actually uses: when etcd is configured it must
         *     answer a maintenance status RPC; in-memory (dev) stores have no
         *     external dependency and report ready immediately.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Ready */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example ready */
                            status?: string;
                            /**
                             * @example {
                             *       "etcd": true
                             *     }
                             */
                            checks?: {
                                [key: string]: boolean;
                            };
                        };
                    };
                };
                /** @description Not ready (a dependency is unreachable) */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example not_ready */
                            status?: string;
                            /**
                             * @example {
                             *       "etcd": false
                             *     }
                             */
                            checks?: {
                                [key: string]: boolean;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authenticate user and get JWT */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description JWT issued */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResponse"];
                    };
                };
                /** @description Missing username or password */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid credentials */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List state snapshots
         * @description Lists available etcd state snapshots (newest first). Requires a
         *     daemon backed by etcd; in-memory (dev) stores report no backups.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of snapshots */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SnapshotInfo"][];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create a state snapshot
         * @description Snapshots the full etcd state to a JSON file on the daemon's backup
         *     directory and prunes snapshots beyond the configured retention.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Snapshot created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SnapshotInfo"];
                    };
                };
                /** @description Backup requires a persistent (etcd) store */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backup/{name}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restore a state snapshot
         * @description Wipes the current etcd state and replays the snapshot, returning the
         *     cluster to the captured configuration.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Snapshot restored */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SnapshotInfo"];
                    };
                };
                /** @description Invalid snapshot name or unsupported format */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Snapshot not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List VMs */
        get: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Tenant scope (required after T0.4 multitenancy) */
                    "X-Tenant-Id"?: components["parameters"]["TenantId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description VM list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VmConfig"][];
                    };
                };
            };
        };
        put?: never;
        /** Create VM */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Tenant scope (required after T0.4 multitenancy) */
                    "X-Tenant-Id"?: components["parameters"]["TenantId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["VmCreate"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VmConfig"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                409: components["responses"]["QuotaExceeded"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vms/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        /** Get VM */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ResourceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description VM details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VmConfig"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        /** Delete VM */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ResourceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vms/{id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start VM */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ResourceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description VM started */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VmConfig"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vms/{id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop VM */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ResourceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description VM stopped */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VmConfig"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vms/{id}/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Snapshot a VM */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ResourceId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name: string;
                    };
                };
            };
            responses: {
                /** @description Snapshot taken */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Snapshot"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vms/{id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore a VM from a snapshot */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ResourceId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        snapshot_id: string;
                    };
                };
            };
            responses: {
                /** @description VM restored */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vms/{id}/clone": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clone a VM or template into a new VM */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ResourceId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name: string;
                    };
                };
            };
            responses: {
                /** @description Cloned VM */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VmConfig"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["QuotaExceeded"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vms/{id}/resize": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resize a VM (cpus / memory, hot on running VMs) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ResourceId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        cpus?: number;
                        memory_mb?: number;
                    };
                };
            };
            responses: {
                /** @description VM resized */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VmConfig"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vms/{id}/hotplug": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Hotplug a device (disk / NIC / CPU) on a running VM
         * @description Adds or removes a disk, NIC or CPU on a running VM without a reboot
         *     (T1.6). A disk `add` with `size_gb` creates a blank qcow2 of that size
         *     and attaches it; a `path` may be supplied instead of creating one. A
         *     disk `remove` targets the disk `id`. A NIC add/remove targets `tap`. A
         *     CPU add/remove resizes to the absolute `cpus` count.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ResourceId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        action: "add" | "remove";
                        /** @enum {string} */
                        resource: "disk" | "nic" | "cpu";
                        /** @description Disk path (disk add; optional — size_gb creates one) */
                        path?: string;
                        /** @description Blank disk size in GB (disk add) */
                        size_gb?: number;
                        /** @description Tap/network name (nic) */
                        tap?: string;
                        /** @description Target CPU count (cpu) */
                        cpus?: number;
                        /** @description Disk id to remove (disk remove) */
                        id?: string;
                    };
                };
            };
            responses: {
                /** @description Device hotplugged; returns the updated VM */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VmConfig"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vms/{id}/memory": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resize a VM's memory in place via balloon (T1.7)
         * @description Adjusts a running VM's live memory within its balloon bounds (min/max)
         *     without a reboot. Rejected with 400 when the target is outside the
         *     VM's balloon range or zero.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ResourceId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        target_mb: number;
                    };
                };
            };
            responses: {
                /** @description Memory resized; returns the updated VM */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VmConfig"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vms/{id}/disks": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        get?: never;
        /** Attach a data disk to a VM */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ResourceId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DiskConfig"];
                };
            };
            responses: {
                /** @description Disk attached */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DiskConfig"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vms/{id}/disks/{disk_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
                disk_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Detach a data disk from a VM */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ResourceId"];
                    disk_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Disk detached */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vms/{id}/nics": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        get?: never;
        /** Attach a NIC to a VM */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ResourceId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        tap: string;
                    };
                };
            };
            responses: {
                /** @description NIC attached */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vms/{id}/nics/{tap}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
                tap: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Detach a NIC from a VM */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ResourceId"];
                    tap: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description NIC detached */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vms/{id}/console": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        /** Get console (VNC/vsock) access URL */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ResourceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Console URL */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConsoleInfo"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List cluster nodes */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Node list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Node"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        /** Register a node */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Node"];
                };
            };
            responses: {
                /** @description Registered */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Node"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nodes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        /** Get a node */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ResourceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Node details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Node"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        /** Remove a node */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ResourceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Removed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nodes/{id}/drain": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        get?: never;
        /** Start or stop draining a node */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ResourceId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        drain: boolean;
                    };
                };
            };
            responses: {
                /** @description Node updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Node"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nodes/{id}/heartbeat": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Node agent heartbeat (liveness + usage report) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ResourceId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["NodeHeartbeat"];
                };
            };
            responses: {
                /** @description Node refreshed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Node"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/networks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List networks */
        get: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Tenant scope (required after T0.4 multitenancy) */
                    "X-Tenant-Id"?: components["parameters"]["TenantId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Network list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Network"][];
                    };
                };
            };
        };
        put?: never;
        /** Create network */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Tenant scope (required after T0.4 multitenancy) */
                    "X-Tenant-Id"?: components["parameters"]["TenantId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["NetworkCreate"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Network"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                409: components["responses"]["QuotaExceeded"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/networks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        /** Get network */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ResourceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Network details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Network"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        /** Delete network */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ResourceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/storage/pools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List storage pools */
        get: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Tenant scope (required after T0.4 multitenancy) */
                    "X-Tenant-Id"?: components["parameters"]["TenantId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Pool list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StoragePool"][];
                    };
                };
            };
        };
        put?: never;
        /** Create storage pool */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Tenant scope (required after T0.4 multitenancy) */
                    "X-Tenant-Id"?: components["parameters"]["TenantId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["StoragePoolCreate"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StoragePool"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                409: components["responses"]["QuotaExceeded"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/storage/pools/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        /** Get storage pool */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Pool details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StoragePool"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        /** Delete storage pool */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/network/routers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List virtual routers */
        get: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Tenant scope (required after T0.4 multitenancy) */
                    "X-Tenant-Id"?: components["parameters"]["TenantId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Router list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VirtualRouter"][];
                    };
                };
            };
        };
        put?: never;
        /** Create virtual router */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Tenant scope (required after T0.4 multitenancy) */
                    "X-Tenant-Id"?: components["parameters"]["TenantId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["VirtualRouter"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VirtualRouter"];
                    };
                };
                400: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/network/routers/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        /** Get virtual router */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Router details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VirtualRouter"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        /** Delete virtual router */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/network/dhcp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List DHCP/DNS servers */
        get: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Tenant scope (required after T0.4 multitenancy) */
                    "X-Tenant-Id"?: components["parameters"]["TenantId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description DHCP server list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DhcpServer"][];
                    };
                };
            };
        };
        put?: never;
        /** Create DHCP/DNS server */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Tenant scope (required after T0.4 multitenancy) */
                    "X-Tenant-Id"?: components["parameters"]["TenantId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DhcpServer"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DhcpServer"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/network/dhcp/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        /** Get DHCP/DNS server */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description DHCP server details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DhcpServer"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        /** Delete DHCP/DNS server */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/network/floating-ips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List floating IPs */
        get: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Tenant scope (required after T0.4 multitenancy) */
                    "X-Tenant-Id"?: components["parameters"]["TenantId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Floating IP list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FloatingIp"][];
                    };
                };
            };
        };
        put?: never;
        /** Allocate floating IP */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Tenant scope (required after T0.4 multitenancy) */
                    "X-Tenant-Id"?: components["parameters"]["TenantId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["FloatingIp"];
                };
            };
            responses: {
                /** @description Allocated */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FloatingIp"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/network/floating-ips/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        /** Get floating IP */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Floating IP details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FloatingIp"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        /** Deallocate floating IP */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deallocated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/s3/buckets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List S3 buckets */
        get: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Tenant scope (required after T0.4 multitenancy) */
                    "X-Tenant-Id"?: components["parameters"]["TenantId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Bucket list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["S3Bucket"][];
                    };
                };
            };
        };
        put?: never;
        /** Create S3 bucket */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Tenant scope (required after T0.4 multitenancy) */
                    "X-Tenant-Id"?: components["parameters"]["TenantId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["S3Bucket"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["S3Bucket"];
                    };
                };
                409: components["responses"]["QuotaExceeded"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/s3/buckets/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        /** Get S3 bucket */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Bucket details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["S3Bucket"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        /** Delete S3 bucket */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/s3/credentials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List S3 access keys */
        get: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Tenant scope (required after T0.4 multitenancy) */
                    "X-Tenant-Id"?: components["parameters"]["TenantId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Access key list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["S3AccessKey"][];
                    };
                };
            };
        };
        put?: never;
        /** Issue S3 credentials */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Tenant scope (required after T0.4 multitenancy) */
                    "X-Tenant-Id"?: components["parameters"]["TenantId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["S3AccessKey"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List registered images */
        get: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Tenant scope (required after T0.4 multitenancy) */
                    "X-Tenant-Id"?: components["parameters"]["TenantId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Image list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Image"][];
                    };
                };
            };
        };
        put?: never;
        /** Register an image */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Tenant scope (required after T0.4 multitenancy) */
                    "X-Tenant-Id"?: components["parameters"]["TenantId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Image"];
                };
            };
            responses: {
                /** @description Registered */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Image"];
                    };
                };
                400: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/images/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Show image */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Image details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Image"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        /** Delete image */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/images/{id}/template": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        /** Set image template flag */
        put: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Tenant scope (required after T0.4 multitenancy) */
                    "X-Tenant-Id"?: components["parameters"]["TenantId"];
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        template?: boolean;
                    };
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["NotFound"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Prometheus metrics scrape endpoint */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Prometheus text exposition */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/push": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Push a metric (daemon/UI) */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Tenant scope (required after T0.4 multitenancy) */
                    "X-Tenant-Id"?: components["parameters"]["TenantId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Metric"];
                };
            };
            responses: {
                /** @description Pushed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/marketplace/apps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List marketplace apps */
        get: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Tenant scope (required after T0.4 multitenancy) */
                    "X-Tenant-Id"?: components["parameters"]["TenantId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description App list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MarketplaceApp"][];
                    };
                };
            };
        };
        put?: never;
        /** Install marketplace app */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Tenant scope (required after T0.4 multitenancy) */
                    "X-Tenant-Id"?: components["parameters"]["TenantId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["MarketplaceAppCreate"];
                };
            };
            responses: {
                /** @description Installed */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MarketplaceApp"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/marketplace/apps/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        /** Get marketplace app */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ResourceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description App details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MarketplaceApp"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        /** Uninstall marketplace app */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ResourceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Uninstalled */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quotas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all tenant quotas */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Quota list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TenantQuota"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quotas/{tenant_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        /** Get tenant quota (unlimited when unset) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tenant_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Tenant quota */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TenantQuota"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        /** Set tenant quota */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tenant_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TenantQuota"];
                };
            };
            responses: {
                /** @description Quota updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TenantQuota"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        post?: never;
        /** Delete tenant quota (back to unlimited) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tenant_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Query audit log
         * @description Records every mutation (who/what/when/tenant). Filters are optional.
         */
        get: {
            parameters: {
                query?: {
                    tenant_id?: string;
                    user?: string;
                    action?: "create" | "read" | "update" | "delete";
                    resource?: string;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Audit entries (most recent first) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuditEntry"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export full audit log as JSON */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Complete append-only audit log */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuditEntry"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SnapshotInfo: {
            /** @example thiscloud-1786957043.json */
            name?: string;
            /** @description Unix timestamp of the snapshot */
            created_at?: number;
            size_bytes?: number;
            /** @description Number of key/value pairs captured */
            entries?: number;
        };
        VmConfig: {
            /** Format: uuid */
            id?: string;
            name?: string;
            cpus?: number;
            memory_mb?: number;
            disk_path?: string;
            kernel?: string;
            kernel_args?: string;
            networks?: string[];
            disks?: components["schemas"]["DiskConfig"][];
            snapshots?: components["schemas"]["Snapshot"][];
            /** @description Cloud-init user-data (cloud-config), applied at next boot */
            cloud_init?: string | null;
            /** @description Boot with UEFI firmware (OVMF) */
            uefi?: boolean;
            /** @description Attach a vTPM device (requires UEFI) */
            tpm?: boolean;
            /** @description Mark VM as a reusable template */
            template?: boolean;
            /** @description Placement node ID. Empty means the best-fit scheduler picks it */
            node?: string;
            /** @description Scheduler affinity labels (node must carry at least one) */
            affinity?: string[];
            /** @description Scheduler anti-affinity labels (node must not carry any) */
            anti_affinity?: string[];
            /** @enum {string} */
            status?: "running" | "stopped" | "error";
            /** @description Owner tenant (set by server) */
            tenant_id?: string;
            /** @description Memory balloon bounds for live memory adjustment (T1.7) */
            balloon?: {
                /** @description Balloon floor — memory never drops below this */
                min_mb?: number;
                /** @description Balloon ceiling — memory never grows above this */
                max_mb?: number;
            };
        };
        VmCreate: {
            name: string;
            cpus: number;
            memory_mb: number;
            disk_path?: string;
            kernel?: string;
            kernel_args?: string;
            networks?: string[];
            /** @description Cloud-init user-data (cloud-config), applied at next boot */
            cloud_init?: string;
            uefi?: boolean;
            tpm?: boolean;
            /** @description Mark VM as a reusable template */
            template?: boolean;
            /** @description Placement node ID. Empty means the best-fit scheduler picks it */
            node?: string;
            affinity?: string[];
            anti_affinity?: string[];
        };
        Snapshot: {
            id: string;
            name: string;
            /** @description UNIX epoch seconds */
            created_at?: string;
        };
        DiskConfig: {
            id?: string;
            path: string;
            size_gb?: number;
        };
        ConsoleInfo: {
            /** @description WebSocket console endpoint (VNC/vsock proxied by the daemon) */
            url: string;
        };
        Node: {
            /** @description Server-assigned node ID */
            id?: string;
            name?: string;
            /** @enum {string} */
            role?: "master" | "worker";
            /** @description ip:port of the node agent */
            address?: string;
            hostname?: string;
            /** @description 0 means unknown/unlimited */
            cpus_total?: number;
            cpus_used?: number;
            /** @description 0 means unknown/unlimited */
            memory_total_mb?: number;
            memory_used_mb?: number;
            vms?: number;
            /** @enum {string} */
            state?: "online" | "offline" | "draining";
            /** @description UNIX epoch of last heartbeat */
            last_seen_secs?: number;
            /** @description Seconds without heartbeat before a node goes offline */
            ttl_secs?: number;
            /** @description Scheduler affinity/anti-affinity labels */
            labels?: string[];
        };
        NodeHeartbeat: {
            cpus_used: number;
            memory_used_mb: number;
            vms: number;
        };
        Network: {
            /** Format: uuid */
            id?: string;
            name?: string;
            /** @example 10.0.0.0/24 */
            cidr?: string;
            gateway?: string;
            vlan?: number | null;
            dns?: string[];
        };
        NetworkCreate: {
            name: string;
            cidr: string;
            gateway: string;
            vlan?: number;
            dns?: string[];
        };
        StoragePool: {
            name?: string;
            /** @enum {string} */
            pool_type?: "linstor" | "drbd" | "local" | "ceph";
            devices?: string[];
            replication?: number;
        };
        StoragePoolCreate: {
            name: string;
            /** @enum {string} */
            pool_type: "linstor" | "drbd" | "local" | "ceph";
            devices?: string[];
            replication: number;
        };
        MarketplaceApp: {
            /** Format: uuid */
            id?: string;
            name?: string;
            /** @enum {string} */
            app_type?: "iso" | "docker" | "cloud-init" | "turbokit" | "k8s";
            source?: string;
            version?: string;
            /** @enum {string} */
            status?: "installed" | "installing" | "error";
        };
        MarketplaceAppCreate: {
            name: string;
            /** @enum {string} */
            app_type: "iso" | "docker" | "cloud-init" | "turbokit" | "k8s";
            source: string;
            version?: string;
        };
        VirtualRouter: {
            /** Format: uuid */
            id?: string;
            name?: string;
            net_id?: string;
            external_net_id?: string;
            /** @default false */
            ha: boolean;
            tenant_id?: string;
            /** @enum {string} */
            status?: "created" | "deleted";
        };
        DhcpServer: {
            /** Format: uuid */
            id?: string;
            name?: string;
            net_id?: string;
            pool_start?: string;
            pool_end?: string;
            dns?: string[];
            tenant_id?: string;
            /** @enum {string} */
            status?: "created" | "deleted";
        };
        FloatingIp: {
            /** Format: uuid */
            id?: string;
            name?: string;
            ip?: string;
            vm_id?: string;
            net_id?: string;
            tenant_id?: string;
        };
        S3Bucket: {
            /** Format: uuid */
            id?: string;
            name?: string;
            tenant_id?: string;
            /** @description UNIX epoch seconds */
            created_at?: number;
        };
        S3AccessKey: {
            access_key?: string;
            secret_key?: string;
            user?: string;
            tenant_id?: string;
        };
        Metric: {
            /** @example thiscloud_vms */
            name: string;
            /** Format: double */
            value: number;
            /** @enum {string} */
            metric_type: "counter" | "gauge";
            labels?: {
                [key: string]: string;
            };
        };
        /** @description Per-tenant resource limits. 0 means unlimited. */
        TenantQuota: {
            tenant_id: string;
            max_cpus?: number;
            max_memory_mb?: number;
            max_vms?: number;
            max_storage_gb?: number;
            max_networks?: number;
        };
        AuditEntry: {
            /** Format: uuid */
            id?: string;
            /** @description Unix epoch seconds */
            timestamp?: string;
            user?: string;
            role?: string;
            tenant_id?: string;
            /** @enum {string} */
            action?: "create" | "read" | "update" | "delete";
            /** @example vm */
            resource?: string;
            resource_id?: string;
            detail?: string;
        };
        LoginRequest: {
            username: string;
            password: string;
        };
        LoginResponse: {
            /** @description JWT Bearer token */
            token?: string;
            /** @enum {string} */
            role?: "admin" | "tenant_user";
            tenant_id?: string;
            /** @description Unix timestamp */
            expires_at?: number;
        };
        Image: {
            /** Format: uuid */
            id?: string;
            name?: string;
            /** @description Artifact location (HTTP(S) URL or local pool path) */
            source?: string;
            /** @description Expected/verified digest at import time */
            sha256?: string;
            /** Format: int64 */
            size_bytes?: number;
            /** @enum {string} */
            format?: "qcow2" | "iso" | "raw" | "cloud-init";
            /** @enum {string} */
            os_family?: "generic" | "alma" | "ubuntu" | "debian" | "fedora" | "rocky";
            version?: string;
            /** @description Reusable as a VM template */
            template?: boolean;
            /** @enum {string} */
            status?: "available" | "importing" | "error";
            /** @description Owner tenant (set by server) */
            tenant_id?: string;
        };
        Error: {
            error?: string;
        };
    };
    responses: {
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Validation error */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Tenant quota exceeded */
        QuotaExceeded: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Missing or invalid JWT token */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Insufficient role permissions */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        ResourceId: string;
        /** @description Tenant scope (required after T0.4 multitenancy) */
        TenantId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
