/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/openapi.yaml": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** This contract (OpenAPI) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The OpenAPI document served by this daemon */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/yaml": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authenticate user and get JWT */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description JWT issued */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResponse"];
                    };
                };
                /** @description Missing username or password */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid credentials */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List VMs */
        get: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Tenant scope (required after T0.4 multitenancy) */
                    "X-Tenant-Id"?: components["parameters"]["TenantId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description VM list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VmConfig"][];
                    };
                };
            };
        };
        put?: never;
        /** Create VM */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Tenant scope (required after T0.4 multitenancy) */
                    "X-Tenant-Id"?: components["parameters"]["TenantId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["VmCreate"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VmConfig"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                409: components["responses"]["QuotaExceeded"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vms/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        /** Get VM */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ResourceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description VM details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VmConfig"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        /** Delete VM */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ResourceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vms/{id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start VM */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ResourceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description VM started */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VmConfig"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vms/{id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop VM */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ResourceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description VM stopped */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VmConfig"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vms/{id}/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Snapshot a VM */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ResourceId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name: string;
                    };
                };
            };
            responses: {
                /** @description Snapshot taken */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Snapshot"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vms/{id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore a VM from a snapshot */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ResourceId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        snapshot_id: string;
                    };
                };
            };
            responses: {
                /** @description VM restored */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vms/{id}/clone": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clone a VM or template into a new VM */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ResourceId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name: string;
                    };
                };
            };
            responses: {
                /** @description Cloned VM */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VmConfig"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["QuotaExceeded"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vms/{id}/resize": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resize a VM (cpus / memory, hot on running VMs) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ResourceId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        cpus?: number;
                        memory_mb?: number;
                    };
                };
            };
            responses: {
                /** @description VM resized */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VmConfig"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vms/{id}/disks": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        get?: never;
        /** Attach a data disk to a VM */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ResourceId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DiskConfig"];
                };
            };
            responses: {
                /** @description Disk attached */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DiskConfig"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vms/{id}/disks/{disk_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
                disk_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Detach a data disk from a VM */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ResourceId"];
                    disk_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Disk detached */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vms/{id}/nics": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        get?: never;
        /** Attach a NIC to a VM */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ResourceId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        tap: string;
                    };
                };
            };
            responses: {
                /** @description NIC attached */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vms/{id}/nics/{tap}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
                tap: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Detach a NIC from a VM */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ResourceId"];
                    tap: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description NIC detached */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vms/{id}/console": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        /** Get console (VNC/vsock) access URL */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ResourceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Console URL */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConsoleInfo"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/networks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List networks */
        get: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Tenant scope (required after T0.4 multitenancy) */
                    "X-Tenant-Id"?: components["parameters"]["TenantId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Network list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Network"][];
                    };
                };
            };
        };
        put?: never;
        /** Create network */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Tenant scope (required after T0.4 multitenancy) */
                    "X-Tenant-Id"?: components["parameters"]["TenantId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["NetworkCreate"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Network"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                409: components["responses"]["QuotaExceeded"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/networks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        /** Get network */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ResourceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Network details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Network"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        /** Delete network */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ResourceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/storage/pools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List storage pools */
        get: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Tenant scope (required after T0.4 multitenancy) */
                    "X-Tenant-Id"?: components["parameters"]["TenantId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Pool list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StoragePool"][];
                    };
                };
            };
        };
        put?: never;
        /** Create storage pool */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Tenant scope (required after T0.4 multitenancy) */
                    "X-Tenant-Id"?: components["parameters"]["TenantId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["StoragePoolCreate"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StoragePool"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                409: components["responses"]["QuotaExceeded"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/storage/pools/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        /** Get storage pool */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Pool details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StoragePool"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        /** Delete storage pool */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/marketplace/apps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List marketplace apps */
        get: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Tenant scope (required after T0.4 multitenancy) */
                    "X-Tenant-Id"?: components["parameters"]["TenantId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description App list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MarketplaceApp"][];
                    };
                };
            };
        };
        put?: never;
        /** Install marketplace app */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Tenant scope (required after T0.4 multitenancy) */
                    "X-Tenant-Id"?: components["parameters"]["TenantId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["MarketplaceAppCreate"];
                };
            };
            responses: {
                /** @description Installed */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MarketplaceApp"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/marketplace/apps/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        /** Get marketplace app */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ResourceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description App details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MarketplaceApp"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        /** Uninstall marketplace app */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ResourceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Uninstalled */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quotas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all tenant quotas */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Quota list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TenantQuota"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quotas/{tenant_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        /** Get tenant quota (unlimited when unset) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tenant_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Tenant quota */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TenantQuota"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        /** Set tenant quota */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tenant_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TenantQuota"];
                };
            };
            responses: {
                /** @description Quota updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TenantQuota"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        post?: never;
        /** Delete tenant quota (back to unlimited) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tenant_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Query audit log
         * @description Records every mutation (who/what/when/tenant). Filters are optional.
         */
        get: {
            parameters: {
                query?: {
                    tenant_id?: string;
                    user?: string;
                    action?: "create" | "read" | "update" | "delete";
                    resource?: string;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Audit entries (most recent first) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuditEntry"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export full audit log as JSON */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Complete append-only audit log */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuditEntry"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        VmConfig: {
            /** Format: uuid */
            id?: string;
            name?: string;
            cpus?: number;
            memory_mb?: number;
            disk_path?: string;
            kernel?: string;
            kernel_args?: string;
            networks?: string[];
            disks?: components["schemas"]["DiskConfig"][];
            snapshots?: components["schemas"]["Snapshot"][];
            /** @description Cloud-init user-data (cloud-config), applied at next boot */
            cloud_init?: string | null;
            /** @description Boot with UEFI firmware (OVMF) */
            uefi?: boolean;
            /** @description Attach a vTPM device (requires UEFI) */
            tpm?: boolean;
            /** @description Mark VM as a reusable template */
            template?: boolean;
            /** @enum {string} */
            status?: "running" | "stopped" | "error";
            /** @description Owner tenant (set by server) */
            tenant_id?: string;
        };
        VmCreate: {
            name: string;
            cpus: number;
            memory_mb: number;
            disk_path?: string;
            kernel?: string;
            kernel_args?: string;
            networks?: string[];
            /** @description Cloud-init user-data (cloud-config), applied at next boot */
            cloud_init?: string;
            uefi?: boolean;
            tpm?: boolean;
            /** @description Mark VM as a reusable template */
            template?: boolean;
        };
        Snapshot: {
            id: string;
            name: string;
            /** @description UNIX epoch seconds */
            created_at?: string;
        };
        DiskConfig: {
            id?: string;
            path: string;
            size_gb?: number;
        };
        ConsoleInfo: {
            /** @description WebSocket console endpoint (VNC/vsock proxied by the daemon) */
            url: string;
        };
        Network: {
            /** Format: uuid */
            id?: string;
            name?: string;
            /** @example 10.0.0.0/24 */
            cidr?: string;
            gateway?: string;
            vlan?: number | null;
            dns?: string[];
        };
        NetworkCreate: {
            name: string;
            cidr: string;
            gateway: string;
            vlan?: number;
            dns?: string[];
        };
        StoragePool: {
            name?: string;
            /** @enum {string} */
            pool_type?: "linstor" | "drbd" | "local" | "ceph";
            devices?: string[];
            replication?: number;
        };
        StoragePoolCreate: {
            name: string;
            /** @enum {string} */
            pool_type: "linstor" | "drbd" | "local" | "ceph";
            devices?: string[];
            replication: number;
        };
        MarketplaceApp: {
            /** Format: uuid */
            id?: string;
            name?: string;
            /** @enum {string} */
            app_type?: "iso" | "docker" | "cloud-init" | "turbokit" | "k8s";
            source?: string;
            version?: string;
            /** @enum {string} */
            status?: "installed" | "installing" | "error";
        };
        MarketplaceAppCreate: {
            name: string;
            /** @enum {string} */
            app_type: "iso" | "docker" | "cloud-init" | "turbokit" | "k8s";
            source: string;
            version?: string;
        };
        /** @description Per-tenant resource limits. 0 means unlimited. */
        TenantQuota: {
            tenant_id: string;
            max_cpus?: number;
            max_memory_mb?: number;
            max_vms?: number;
            max_storage_gb?: number;
            max_networks?: number;
        };
        AuditEntry: {
            /** Format: uuid */
            id?: string;
            /** @description Unix epoch seconds */
            timestamp?: string;
            user?: string;
            role?: string;
            tenant_id?: string;
            /** @enum {string} */
            action?: "create" | "read" | "update" | "delete";
            /** @example vm */
            resource?: string;
            resource_id?: string;
            detail?: string;
        };
        LoginRequest: {
            username: string;
            password: string;
        };
        LoginResponse: {
            /** @description JWT Bearer token */
            token?: string;
            /** @enum {string} */
            role?: "admin" | "tenant_user";
            tenant_id?: string;
            /** @description Unix timestamp */
            expires_at?: number;
        };
        Error: {
            error?: string;
        };
    };
    responses: {
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Validation error */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Tenant quota exceeded */
        QuotaExceeded: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Missing or invalid JWT token */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Insufficient role permissions */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        ResourceId: string;
        /** @description Tenant scope (required after T0.4 multitenancy) */
        TenantId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
